name: GAN_EXPR_Template
model_type: AnimeSISRGANModel
scale: 2
num_gpu: 1
manual_seed: 0

datasets:
  train:
    name: AnimeSISRDatasetTrain
    type: AnimeSISRDataset
    dataroot_gt: D:/program/datasets/AnimeSISR/mixed/cropped/images
    dataroot_en: D:/program/datasets/AnimeSISR/mixed/cropped/sketch_ld_enhanced
    image_mode: RGB

    pixel_gt: gt
    edge_gt: en
    perceptual_gt: en
    gan_gt: gt

    enable_rcas_sharpening: false
    enable_usm_sharpening: false
    opencl_pid: 1
    opencl_did: 0

    degrade_type: animesisr_test

    use_shuffle: true
    persistent_workers: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: AnimeSISRDatasetVal
    type: AnimeSISRDataset
    dataroot_gt: D:/program/datasets/ModernAnimation1080_v3/valHR
    image_mode: RGB

    degrade_type: bicubic

network_g:
  type: RRDBNet
  num_in_ch: 1
  num_out_ch: 1
  scale: 2
  num_feat: 64
  num_block: 6
  num_grow_ch: 32

network_d:
  type: MultiScaleDiscriminator
  num_in_ch: 3

path:
  pretrain_network_g: experiments/l1_trained_models/RRDB_Net_6B_RGB_LD_AnimeSISR_Test.pth
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 200000
  warmup_iter: -1

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  edge_opt:
    type: SobelEdgeLoss
    loss_weight: 1.0

  perceptual_opt:
    type: APISRPerceptualLoss
    loss_weight: 1.0

  gan_opt:
    type: MultiScaleGANLoss
    gan_type: lsgan
    loss_weight: 0.2

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 10000
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
    niqe:
      type: calculate_niqe
      crop_border: 4

logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 20000
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
