name: PSNR_SSIM_NIQE_Distill_Expr_Template
model_type: AnimeSISRDistillModel
scale: 2
num_gpu: 1
manual_seed: 0

datasets:
  train:
    name: AnimeSISRDatasetTrain
    type: AnimeSISRDataset
    dataroot_gt: D:/program/datasets/ModernAnimation1080_v3/cropped/images
    image_mode: L

    enable_rcas_sharpening: false
    enable_usm_sharpening: false
    opencl_pid: 0
    opencl_did: 0

    degrade_type: bicubic

    use_shuffle: true
    persistent_workers: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: AnimeSISRDatasetVal
    type: AnimeSISRDataset
    dataroot_gt: D:/program/datasets/ModernAnimation1080_v3/valHR
    image_mode: L

    degrade_type: bicubic

network_g:
  type: ARNet_Best
  num_in_ch: 1
  num_out_ch: 1
  scale: 2
  num_feat: 8
  num_block: 8
  rep_conv3x3_block_name: rrrb

network_t:
  type: ARNet_Best
  num_in_ch: 1
  num_out_ch: 1
  scale: 2
  num_feat: 64
  num_block: 16
  rep_conv3x3_block_name: plain

path:
  pretrain_network_t: D:\program\code\python\AnimeSISR\experiments\ARNet_Best_Net_64F_16B_GRAY_PLAIN_MA1080V3_BICUBIC\models\net_g_latest.pth
  param_key_t: params_ema
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 150000, 200000, 250000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1

  distill_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  pixel_opt:
    type: L1Loss
    loss_weight: 0.1
    reduction: mean

val:
  val_freq: !!float 10000
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
    niqe:
      type: calculate_niqe
      crop_border: 4

logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 10000
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
